/*---------------------------------------------------------------------------------------
Nombre del autor: Gerardo Fructuoso Vidal-Aragón
Nombre de la base de datos: ArteVidaCultural
-----------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------
Definición de la estructura de la base de datos
--------------------------------------------------------------------------------------------------*/
/* ------------------ INICIO CREACIÓN BASE DE DATOS -------------------------------------*/
DROP DATABASE IF EXISTS ArteVidaCultural; 
CREATE DATABASE ArteVidaCultural; 
USE ArteVidaCultural; 
/* ------------------ FIN CREACIÓN BASE DE DATOS ----------------------------------------*/
/*------------------- INICIO CREACIÓN DE TABLAS -----------------------------------------*/
CREATE TABLE ACTIVIDAD(
ACTI_CODIGO INT AUTO_INCREMENT NOT NULL, -- LE PONEMOS QUE SE VAYA INCREMENTANDO SOLO TODOS LOS IDS DE LAS TABLAS 
ACTI_COSTE DOUBLE NOT NULL,
ACTI_TIPO VARCHAR (50), 
ACTI_NOMBRE VARCHAR (100) NOT NULL,
PRIMARY KEY(ACTI_CODIGO)
);

CREATE TABLE UBICACIONES(
UBIC_CODIGO INT AUTO_INCREMENT NOT NULL,
UBIC_NOMBRE VARCHAR(50) NOT NULL,
UBIC_DIRE VARCHAR(50) NOT NULL UNIQUE,
UBIC_CIUDAD_PUEBLO VARCHAR (50), 
UBIC_AFORO INT NOT NULL,
UBIC_PRECIO DOUBLE NOT NULL,
UBIC_CARASTERÍSTICAS VARCHAR(200),
PRIMARY KEY(UBIC_CODIGO)
);

CREATE TABLE EVENTO( 
EVEN_CODIGO INT AUTO_INCREMENT NOT NULL, 
EVEN_DESCRIPCION VARCHAR(50), 
EVEN_NOMBRE VARCHAR(50) NOT NULL, 
EVEN_PRECIO_ENTR DOUBLE NOT NULL, 
EVEN_FECHA DATE NOT NULL,
EVEN_HORA TIME NOT NULL, 
EVEN_ACTI_CODIGO INT, 
EVEN_UBIC_CODIGO INT, 
PRIMARY KEY(EVEN_CODIGO), 
FOREIGN KEY(EVEN_ACTI_CODIGO) REFERENCES ACTIVIDAD(ACTI_CODIGO), 
FOREIGN KEY(EVEN_UBIC_CODIGO) REFERENCES UBICACIONES(UBIC_CODIGO) 
);

CREATE TABLE ASISTENTES(
ASIS_CODIGO INT AUTO_INCREMENT NOT NULL,
ASIS_NOMBRE VARCHAR(50) NOT NULL,
ASIS_APELLIDO VARCHAR(50) NOT NULL,
PRIMARY KEY (ASIS_CODIGO)
);

CREATE TABLE ASIS_TELEFONO(
ASIS_CODIGO INT NOT NULL,
ASIS_PREFIJO VARCHAR(4) NOT NULL,
ASIS_TELEFONO VARCHAR(15) NOT NULL,
CONSTRAINT ASIS_PREFIJO CHECK(REGEXP_LIKE(ASIS_PREFIJO, '^\\+[0-9]{1,3}$')),
CONSTRAINT ASIS_TELEFONO CHECK (REGEXP_LIKE(ASIS_TELEFONO, '^[0-9]{8,15}$')),
PRIMARY KEY(ASIS_CODIGO, ASIS_PREFIJO, ASIS_TELEFONO),
FOREIGN KEY (ASIS_CODIGO) REFERENCES ASISTENTES(ASIS_CODIGO)
);

CREATE TABLE ASIS_EMAIL(
ASIS_CODIGO INT NOT NULL,
ASIS_EMAIL VARCHAR(320) NOT NULL,
CONSTRAINT ASIS_EMAIL CHECK (REGEXP_LIKE(ASIS_EMAIL, '^[^@]{1,64}@[^\@]{1,255}$')),
PRIMARY KEY(ASIS_CODIGO, ASIS_EMAIL),
FOREIGN KEY (ASIS_CODIGO) REFERENCES ASISTENTES(ASIS_CODIGO)
);

CREATE TABLE ARTISTA(
ARTI_CODIGO INT AUTO_INCREMENT NOT NULL,
ARTI_BIOGRAFIA VARCHAR(255),
ARTI_NOMBRE VARCHAR(50) NOT NULL,
PRIMARY KEY(ARTI_CODIGO)
);

CREATE TABLE PARTICIPAN(
PART_ACTI_CODIGO INT NOT NULL,
PART_ARTI_CODIGO INT NOT NULL,
LA_CACHE DOUBLE NOT NULL,
PRIMARY KEY(PART_ACTI_CODIGO, PART_ARTI_CODIGO),
FOREIGN KEY(PART_ACTI_CODIGO) REFERENCES ACTIVIDAD(ACTI_CODIGO),
FOREIGN KEY(PART_ARTI_CODIGO) REFERENCES ARTISTA(ARTI_CODIGO)
);

CREATE TABLE ASISTENCIA(
ASIS_EVEN_CODIGO INT NOT NULL,
ASIS_ASIS_CODIGO INT NOT NULL,
PRIMARY KEY(ASIS_EVEN_CODIGO,ASIS_ASIS_CODIGO),
FOREIGN KEY(ASIS_EVEN_CODIGO) REFERENCES EVENTO(EVEN_CODIGO),
FOREIGN KEY(ASIS_ASIS_CODIGO) REFERENCES ASISTENTES(ASIS_CODIGO)
);
/* ------------------- FIN CREACIÓN DE TABLAS ---------------------------------*/

/*------------------------------------------------------------------------------------------------------
Trigger
Inserción de datos
-------------------------------------------------------------------------------------------------------*/
/*
Insertamos los datos desde los archivos que ya vienen preparados.
Estos archivos se encuentran dentro de la ruta:'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\'
*/
-- Para saber en la ruta donde se tienen que agregar los archivos 
SELECT @@GLOBAL.SECURE_FILE_PRIV;
-- Una vez tenemos bien configurado todo, empezamos insertando por ejemplo los de actividad
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Actividades.csv'
INTO TABLE ACTIVIDAD
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;
-- Ahora vamos con la de Ubicaciones
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Ubicaciones.csv'
INTO TABLE UBICACIONES
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

-- Ahora vamos con la de eventos
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Eventos.csv'
INTO TABLE EVENTO
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;
-- Ahora vamos con la de Asistentes
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Asistentes.csv'
INTO TABLE ASISTENTES
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

-- Ahora vamos con la de Asis_telefono
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Asis_telefono.csv'
INTO TABLE ASIS_TELEFONO
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;
-- Ahora vamos con la de Asis_email
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Asis_email.csv'
INTO TABLE ASIS_EMAIL
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;
-- Ahora vamos con la de Artista
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Artista.csv'
INTO TABLE ARTISTA
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;
-- Ahora vamos con la de Participan
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Participan.csv'
INTO TABLE PARTICIPAN
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS; 
-- Ahora vamos con la de Asistencia
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Asistencia.csv'
INTO TABLE ASISTENCIA
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS; 

-- PROBAMOS QUE LOS DATOS INSERTADOS SON CORRECTOS:
SELECT * FROM ACTIVIDAD;
SELECT * FROM UBICACIONES;
SELECT * FROM EVENTO;
SELECT * FROM ASISTENTES;
SELECT * FROM ASIS_TELEFONO;
SELECT * FROM ASIS_EMAIL;
SELECT * FROM ARTISTA;
SELECT * FROM PARTICIPAN;
SELECT * FROM ASISTENCIA;

-- AHORA PROCEDEMOS A CREAR LOS TRIGGERS QUE SEAN NECESARIOS
-- CREAMOS UN TRIGGER PARA VER SI A LA HORA DE CREAR UN EVENTO EN LA MISMA UBICACION Y HORA HAY UNO YA CREADO:
-- PONEMOS UN MINIMO DE QUE UN EVENTO DURA 5 HORAS
DELIMITER //
DROP TRIGGER IF EXISTS COLAPSO_EVENTOS//
CREATE TRIGGER COLAPSO_EVENTOS
BEFORE INSERT ON EVENTO
FOR EACH ROW
BEGIN
	IF EXISTS(
		SELECT 1
		FROM EVENTO
		WHERE EVEN_UBIC_CODIGO = NEW.EVEN_UBIC_CODIGO
		AND EVEN_FECHA = NEW.EVEN_FECHA
		AND EVEN_HORA BETWEEN DATE_SUB(NEW.EVEN_HORA, INTERVAL 5 HOUR) AND DATE_ADD(NEW.EVEN_HORA, INTERVAL 5 HOUR)
	) THEN
    SIGNAL SQLSTATE '23000'
    SET MESSAGE_TEXT = " YA EXISTE UN EVENTO EN ESA UBI Y FECHA";
	END IF;
END//
DELIMITER ;

-- PROBAMOS QUE VA BIEN:
/*
INSERT INTO EVENTO(EVEN_DESCRIPCION, EVEN_NOMBRE, EVEN_PRECIO_ENTR, EVEN_FECHA, EVEN_HORA, EVEN_ACTI_CODIGO, EVEN_UBIC_CODIGO)
VALUES ('Prueba no inserta','Prueba no inserta', 0,'2026-03-16','12:00:00',1,1);

INSERT INTO EVENTO(EVEN_DESCRIPCION, EVEN_NOMBRE, EVEN_PRECIO_ENTR, EVEN_FECHA, EVEN_HORA, EVEN_ACTI_CODIGO, EVEN_UBIC_CODIGO)
VALUES ('Prueba no inserta2','Prueba no inserta2', 0,'2026-03-16','10:00:00',1,1);
*/
-- Funciona correctamente, pero se comenta para que de fallo con el script ya que funciona correctamente

/*------------------------------------------------------------------------------------------------------
Consultas, modificaciones, borrados y vistas con enunciado
-------------------------------------------------------------------------------------------------------*/

/* 
Comenzamos con copnsultas sencillas a tablas simples
*/

-- Por ejemplo, vamos a ver los distintos tipos de actividades que hay:
SELECT DISTINCT(ACTI_TIPO) AS TIPO_DE_ACTIVIDAD FROM ACTIVIDAD;

-- Por ejemplo, vamos a ver las distintas ubicaciones que hay:
SELECT UBIC_NOMBRE AS DISTINTAS_UBICACIONES, UBIC_DIRE AS DISTINTAS_DIRECCIONES, UBIC_CIUDAD_PUEBLO AS DISTINTAS_CIUDADES
FROM UBICACIONES;

-- Por ejemplo ahora vamos a ver los precios de las entradas de los eventos ordenados de mayor a menor (con su nombre)
SELECT EVEN_PRECIO_ENTR AS PRECIO_EVENTO, EVEN_NOMBRE AS NOMBRE_EVENTO FROM EVENTO
ORDER BY EVEN_PRECIO_ENTR ASC;

/* 
Comenzamos con consultas mas complejas (usando where y join)
*/
-- Por ejemplo, vamos a ver a que actividades àrticipan que artistas cuyo caché es mayor a 15
SELECT ARTI_NOMBRE AS NOMBRE_DEL_ARTISTA, ACTI_NOMBRE AS NOMBRE_DE_ACTIVIDAD, LA_CACHE AS CACHE_ARTISTA
FROM ARTISTA
INNER JOIN PARTICIPAN 
ON ARTI_CODIGO = PART_ARTI_CODIGO
INNER JOIN ACTIVIDAD
ON ACTI_CODIGO = PART_ACTI_CODIGO
WHERE LA_CACHE > 10;

-- Por ejemplo vamos a ver la cantidad generada de dinero con las entradas. (Evento, asistencia)
SELECT EVEN_NOMBRE AS NOMBRE_EVENTO, EVEN_PRECIO_ENTR * COALESCE(COUNT(DISTINCT(ASIS_ASIS_CODIGO)), 0) AS GANANCIAS
FROM EVENTO
LEFT JOIN ASISTENCIA
ON EVEN_CODIGO = ASIS_EVEN_CODIGO
GROUP BY EVEN_NOMBRE, EVEN_PRECIO_ENTR
ORDER BY GANANCIAS DESC;

-- Por ejemplo, ahora vamos a crear una vista para obtener el nombre, telefono (el primero que encontremos) y email (primero que encontremos) de los asistentes
DROP VIEW IF EXISTS VI_DATOS_ASISTENTES;
CREATE VIEW VI_DATOS_ASISTENTES AS
SELECT DISTINCT(A.ASIS_CODIGO) AS ASIS_CODIGO, A.ASIS_NOMBRE AS ASIS_NOMBRE, 
MIN(CONCAT(T.ASIS_PREFIJO,' ', T.ASIS_TELEFONO)) AS ASIS_TELEFONO, MIN(E.ASIS_EMAIL) AS ASIS_EMAIL
FROM ASISTENTES A
LEFT JOIN ASIS_TELEFONO T
ON A.ASIS_CODIGO = T.ASIS_CODIGO
LEFT JOIN ASIS_EMAIL E
ON A.ASIS_CODIGO = E.ASIS_CODIGO
GROUP BY ASIS_CODIGO, ASIS_NOMBRE;

SELECT * FROM VI_DATOS_ASISTENTES;



-- Por ejemplo, vamos a ver ahora a que ubicaciones tienen que ir los asistentes según el evento al que tienen que ir, incluyendo su email y telefono
-- Para esto, usamos la vista recientemente creada
SELECT EVEN_NOMBRE AS NOMBRE_EVENTO, UBIC_NOMBRE AS NOMBRE_UBICACION, UBIC_DIRE AS DIRECCION_UBICACION,
ASIS_NOMBRE AS NOMBRE_ASISTENTE, ASIS_TELEFONO AS TELEFONO_ASISTENTE, ASIS_EMAIL AS EMAIL_ASISTENTE
FROM EVENTO
INNER JOIN UBICACIONES
ON UBIC_CODIGO = EVEN_UBIC_CODIGO
INNER JOIN ASISTENCIA
ON ASIS_EVEN_CODIGO = EVEN_CODIGO
INNER JOIN VI_DATOS_ASISTENTES
ON ASIS_CODIGO = ASIS_ASIS_CODIGO
ORDER BY NOMBRE_EVENTO;

-- Por ejemplo vamos a ver la cantidad de asistentes por cada uno de los eventos
SELECT EVEN_NOMBRE AS NOMBRE_EVENTO, COUNT(ASIS_ASIS_CODIGO) AS CANTIDAD_ASISTENTES
FROM EVENTO
LEFT JOIN ASISTENCIA
ON EVEN_CODIGO = ASIS_EVEN_CODIGO
GROUP BY EVEN_NOMBRE
ORDER BY CANTIDAD_ASISTENTES DESC;

-- Por ejmeplo, vamos a ver que artistas asisten a que eventos
SELECT EVEN_NOMBRE AS NOMBRE_EVENTO, ARTI_NOMBRE AS NOMBRE_ARTISTA
FROM EVENTO
INNER JOIN ACTIVIDAD
ON ACTI_CODIGO = EVEN_ACTI_CODIGO
INNER JOIN PARTICIPAN 
ON PART_ACTI_CODIGO = ACTI_CODIGO
INNER JOIN ARTISTA
ON PART_ARTI_CODIGO = ARTI_CODIGO
ORDER BY NOMBRE_ARTISTA;

-- VAMOS A HACER UN INSERT DE PRUEBA (NUEVA UBICACION)
INSERT INTO UBICACIONES(UBIC_NOMBRE, UBIC_DIRE, UBIC_CIUDAD_PUEBLO, UBIC_AFORO,UBIC_PRECIO) 
VALUES("MONCLOA", "CALLE ISAAC PERAL", "MADRID", 100, 200);

-- comprobamos su correcta inserccion:
SELECT * FROM UBICACIONES WHERE UBIC_NOMBRE = 'MONCLOA';

-- POr ejemplo ahora vemos cuantos telefonos tienen cada uno de los asistentes
SELECT A.ASIS_NOMBRE AS NOMBRE_ASISTENTE, COALESCE(COUNT(B.ASIS_TELEFONO),0)
FROM ASISTENTES A
LEFT JOIN ASIS_TELEFONO B
ON A.ASIS_CODIGO = B.ASIS_CODIGO
GROUP BY A.ASIS_NOMBRE;

-- POR EJEMPLO HACEMOS LO MISMO CON LOS CORREOS

SELECT A.ASIS_NOMBRE AS NOMBRE_ASISTENTE, COALESCE(COUNT(B.ASIS_EMAIL),0)
FROM ASISTENTES A
LEFT JOIN ASIS_EMAIL B
ON A.ASIS_CODIGO = B.ASIS_CODIGO
GROUP BY A.ASIS_NOMBRE;

-- Por ejemplo obejetenmos los eventos que haya el 18 de marzo del 2026 Y SUS HORAS

SELECT EVEN_NOMBRE AS NOMBRE_EVENTO, EVEN_HORA AS HORA_EVENTO
FROM EVENTO
WHERE EVEN_FECHA = '2026-03-16';
-- POR EJEMPLO OBTENERMOS LAS FECHAS CON LAS CANTIDADES DE EVENTOS QUE HAY EN DICHAS FECHAS
SELECT COUNT(DISTINCT(EVEN_CODIGO)) AS CANTIDAD_EVENTOS, EVEN_FECHA AS FECHA_EVENTO
FROM EVENTO
GROUP BY EVEN_FECHA;