/*
- UNIQUE KEY(CAMPO1,campo2,....campon) -> Sirve para cuando hya más de una clave primaria, para hacer una única clave primaria y dejar el resto como claves únicas
- FOREIGN KEY(CAMPO) -> Cuando se usa la clave primaria de una tabla en otra tabla. Va acompañado siempre de 'REFERENCES TABLA(CAMPO)'
- PRIMARY KEY(CAMPO1,campo2,....campon) -> Para identificar la clave primera de una tabla (el distintivo único)
- ON DELETE CASCADE: Sirve para actualizar un campo (que viene de una foreign key) cuando se ha borrado dicho registro de la otra tabla
- ON UPDATE CASCADE: Sirve para actualizar un campo (que viene de una foreign key) cuando se ha actualizado dicho registro de la otra tabla
- ON DELETE RESTRICT: Sirve para eliminar un registro (que viene de una foreign key) cuando se ha borrado dicho registro de la otra tabla
- CHECK: Cuando creamos un campo, se puede poner este atributo a la derecha de su declaración para ver si cumple con los requisitos del campo. Por ejemplo: Si tengo un campo que es número de teléfono, este campo (en españa) no debe superar más de nueve dígitos, no puede empezar por 0,...:
    telefono varchar(9) not null check (telefono REGEXP '^[0-9]{9}$')
- DEFAULT: Cuando creamos un campo, se puede pponer este atributo a la derecha de si declaración indicando con que valor quiere que empieze. Ejemplo:
    telefono varchar(9) default '999999999'
*/


/*Inicio de creaciones de bases de datos y de tablas (Language LDD)*/
DROP DATABASE IF EXISTS PINACOTECAS;
CREATE DATABASE PINACOTECAS;
USE PINACOTECAS;
CREATE TABLE PINTOR(
PINT_CODIGO SMALLINT AUTO_INCREMENT,
PINT_NOMBRE VARCHAR(50),
PINT_PAIS VARCHAR(50),
PINT_CIUDAD VARCHAR(50),
PINT_FEC_NAC DATE,
PINT_FEC_DEF DATE,
PINT_COD_MAESTRO SMALLINT,
PRIMARY KEY(PINT_CODIGO),
FOREIGN KEY(PINT_COD_MAESTRO) REFERENCES PINTOR(PINT_CODIGO)
ON DELETE SET NULL
ON UPDATE CASCADE
);
CREATE TABLE MECENAS(
MECE_CODIGO SMALLINT AUTO_INCREMENT,
MECE_NOMBRE VARCHAR(50),
MECE_PAIS VARCHAR(50),
MECE_FEC_NAC DATE,
MECE_FEC_DEF DATE,
PRIMARY KEY(MECE_CODIGO)
);
CREATE TABLE PINACOTECA(
PINA_NOMBRE VARCHAR(50),
PINA_CIUDAD VARCHAR(50),
PINA_DIRECCION VARCHAR(100),
PINA_SUPERFICIE VARCHAR(50),
PRIMARY KEY(PINA_NOMBRE)
);
CREATE TABLE CUADRO(
CUAD_CODIGO SMALLINT AUTO_INCREMENT,
CUAD_NOMBRE VARCHAR(50),
CUAD_ALTO DOUBLE,
CUAD_ANCHO DOUBLE,
CUAD_FECHA DATE,
CUAD_TECNICA VARCHAR(50),
CUAD_PINT_CODIGO SMALLINT,
CUAD_PINA_NOMBRE VARCHAR(50),
PRIMARY KEY(CUAD_CODIGO),
FOREIGN KEY(CUAD_PINT_CODIGO) REFERENCES PINTOR(PINT_CODIGO)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(CUAD_PINA_NOMBRE) REFERENCES PINACOTECA(PINA_NOMBRE)
ON DELETE RESTRICT
ON UPDATE CASCADE
);
CREATE TABLE ESCUELA(
ESCU_NOMBRE VARCHAR(50),
ESCU_PAIS VARCHAR(50),
ESCU_FEC_APARICION DATE,
PRIMARY KEY(ESCU_NOMBRE)
);
CREATE TABLE PROTEGE(
PROT_MECE_CODIGO SMALLINT,
PROT_PINT_CODIGO SMALLINT,
PRIMARY KEY(PROT_MECE_CODIGO,PROT_PINT_CODIGO),
FOREIGN KEY(PROT_PINT_CODIGO) REFERENCES PINTOR(PINT_CODIGO)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(PROT_MECE_CODIGO) REFERENCES MECENAS(MECE_CODIGO)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE PERTENECE(
PERT_PINT_CODIGO SMALLINT,
PERT_ESCU_NOMBRE VARCHAR(50),
PRIMARY KEY(PERT_PINT_CODIGO),
FOREIGN KEY(PERT_PINT_CODIGO) REFERENCES PINTOR(PINT_CODIGO)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(PERT_ESCU_NOMBRE) REFERENCES ESCUELA(ESCU_NOMBRE)
ON DELETE CASCADE
ON UPDATE CASCADE
);
/*Fin de creaciones de bases de datos y de tablas (Language LDD)*/

/* Inicio de creacion de elementos en tablas (Language LMD)*/
/* Ejemplos de insert:
2 formas:
	- INSERT INTO X VALUES ('',...., NCAMPOS)
    - INSERT INTO X (CAMPO1, CAMPO3) VALUES ('','')
La primera forma es para rellenar todos los campos
La segunda forma es para insertar solo los campos específicos (deberían estar los imprensindibles)
*/
/* INSERTS*/
-- Ejemplo 1 de insert:
INSERT INTO PINTOR VALUES (1,'NOMBRE_PINTOR','NOMBRE_PAIS', 'NOMBRE_CIUDAD','01-01-0001','01-01-0001',NULL); -- Preguntar esta duda de porque sale con fecha 2001
-- Ejemplo 2 de insert:
INSERT INTO PINTOR(PINT_NOMBRE,PINT_PAIS,PINT_CIUDAD,PINT_FEC_NAC,PINT_COD_MAESTRO) VALUES ('JERRY','ESPANA','MADRID','2025-01-01',1);
/* FIN INSERTS*/
/*SELECTS*/
/*Estructura select:
SELECT [*=TODO/CAMPO1,...,CAMPON]
FROM [TABLA]
WHERE [CONDICION]
GROUP BY [NOMBRE_CAMPO] (PARA AGRUPAR CUANDO HAY VARIOS REGISTROS CON UN CAMPO SIMILAR. POR EJEMPLO, QUIERO AGRUPAR POR PARTIDOS (GROUP BY PARTIDO) Y ME SALDRÍAN AGRUPADOS POR PARTIDOS
HAVING (CONDICION) EJEMPLO: HAVING COUNT(*) > 1 (QUE HAYA AL MENOS UNO DE LOS CAMPOS CON MÁS DE UN REGISTRO)
ORDER BY [NOMBRE_CAMPO] PARA ORDENAR LOS REGISTROS SEGUN X CAMPO (ASC/DESC)
LIMIT [NUMERO] SIRVE PARA QUE SAQUE X NUMERO DE REGISTROS COMO MAXIMO
*/
SELECT * FROM PINTOR; -- ME SACA TODOS LOS REGISTROS DE ESTA TABLA
SELECT * FROM PINTOR WHERE PINT_FEC_NAC > '0001-01-01'; -- ME SACA TODOS LOS REGISTROS DONDE EL PINTOS HAYA NACIDO MÁS TARDE DEL 1 DE ENERO DEL 26
SELECT * FROM PINTOR GROUP BY PINT_COD_MAESTRO; -- ME SACA TODOS LOS PINTORES PERO AGRUPADOS POR MAESTRO (PRIMERO TODOS LOS PINTORES DE X MAESTRO Y LUEGO LOS DE Y MAESTRO)
SELECT * FROM PINTOR HAVING COUNT(PINT_COD_MAESTRO) > 1; -- ME SACA TODOS LOS PINTORES CUYOS MAESTROS TENGAN MÁS DE UN PINTOR COMO DISCÍPULO
SELECT * FROM PINTOR LIMIT 1; -- ME SACA SOLO EL PRIMER PINTOR (SOLO SACA 1 REGISTRO)
-- TAMBIÉN SE PUEDEN HACER OPERACIONES ARITMETICAS Y CALCULOS CON FECHAS:
SELECT TIMESTAMPDIFF(YEAR,'2000-01-01',CURDATE()) ANNOSTRASCURRIDOS;
SELECT 4+5*3 AS 'MIOPERACION';
SELECT NOW() - INTERVAL 5 YEAR;
-- FIN OPERACIONES
SELECT * FROM PINTOR WHERE PINT_NOMBRE LIKE '%NOMBRE%'; -- PARA OBTENER AQUELLOS CUYOS NOMBRES CONTENGAN 'NOMBRE'
SELECT * FROM PINTOR WHERE PINT_NOMBRE LIKE 'NOMBRE_PINTOR'; -- PARA OBTENER AQUEL PINTOR CUYO NOMBRE EMPIEZA `POR NOMBRE Y ACABA POR PINTOR Y TIENE UN ACRACTER DESCONOCIDO EN MEDIO
-- PARA SACAR AQUELLOS PINTORS MAYORES DE 18 AÑOS:
SELECT * FROM PINTOR WHERE YEAR(CURDATE()) - YEAR(PINT_FEC_NAC) > 18;
-- PARA SACAR AQUELLOS PINTORS MAYORES DE 18 AÑOS Y MENORS QUE 20:
SELECT * FROM PINTOR WHERE TIMESTAMPDIFF(YEAR, PINT_FEC_NAC, CURDATE()) BETWEEN 18 AND 20;
-- COMENZAMOS CON LOS JOINS:
-- OBTENEMOS TODOS LOS CUADROS DEL PINTOR CON COD 1 CON LA INFO DEL PINTOR:
SELECT * FROM PINTOR
INNER JOIN CUADRO
ON PINT_CODIGO = CUAD_PINT_CODIGO
WHERE PINT_CODIGO = 1;
/*FIN SELECTS*/

/*INICIO FUNCIONES AGREGADAS*/
/*
LAS FUNCIONES AGREGADAS SON PARA OPERAR CON VALORES Y CAMPOS DE LAS TABLAS Y DEVUELVEN UN SOLO VALOR
SON:
AVG(CAMPO) -> SIRVE PARA DEVOLVER LA MEDIA DE TODOS LOS VALORES DE LOS REGISTROS DE LOS CAMPOS (NUMÉRICOS)
MIN(CAMPO) -> SIRVE PARA DEVOLVER EL VALOR MÁS BAJO DE TODOS LOS REGISTROS DE UN CAMPO
MAX(CAMPO) -> SIRVE PARA DEVOLVER EL VALOR MÁS ALTO DE TODOS LOS REGISTROS DE UN CAMPO
SUM(CAMPO) -> SIRVE PARA DEVOLVER LA SUMA DE TODOS LOS VALORES DE LOS REGISTROS DE UN CAMPO
COUNT(CAMPO) -> SIRVE PARA DEVOLVER LA CANTIDAD DE FILAS NO NULAS

ESTAS NO SE PUEDEN PONER EN WHERE, CON LO QUE HABRÍA QUE HACER QUERIES ANIDADAS (POCO EFICIENTES, VER SI SE PUEDE RESOLVER CON INNER)

HAY QUE AGREGAR COALESCE CUANDO LOS CAMPOS PUEDEN VERNI COMO NULL PARA EVITAR PROBLEMAS: COALESCE (SUM(CAMPO), 0) -> DEVUELVE 0 CUANDO ES NULL

*/
-- Ejemplo obtener la media de ancho y alto de los cuadros:
SELECT AVG(CUAD_ANCHO)
FROM CUADRO;
SELECT AVG(CUAD_ALTO)
FROM CUADRO;
-- EJEMPLO OBTENER MINIMO Y MAXIMO DE ANCHO Y ALTO DE LOS CUADROS:
SELECT MIN(CUAD_ANCHO)
FROM CUADRO;
SELECT MAX(CUAD_ALTO)
FROM CUADRO; 
-- EJEMPLO OBTENER SUMA Y CANTIDAD TOTAL DE FILAS DE ANCHO Y ALTO DE LOS CUADROS:
SELECT SUM(CUAD_ANCHO)
FROM CUADRO;
SELECT COUNT(*) FROM CUADRO;
/*FIN FUNCIONES AGREGADAS*/

/* VISTAS*/
/*
Las vistas sirven para crear una vista especial para una tabla (como una tabla nueva). Es decir, se hace un select que se quiere
por ejemplo obtener los pintores mayores de 18 años, y esta vista haría referencia a la tabla principal de pintores pero con esta
condición siempre

*/

-- Ejemplop vista con pintores mayores de 18:
DROP VIEW IF EXISTS V_PINTOR_MAYOR;
CREATE VIEW V_PINTOR_MAYOR AS
SELECT * FROM PINTOR WHERE YEAR(CURDATE()) - YEAR(PINT_FEC_NAC) > 18;
-- Buscamos la tabla y solo nos proporciona los mayores de 18
SELECT * FROM PINTOR;
SELECT * FROM V_PINTOR_MAYOR;

/*FIN VISTAS*/

/* TRIGGERS */
/* 
Los triggers son para que cuando se cumpla cierta condición dada, se lance la acción que tiene el trigger
La estructura de creación de un trigger es la siguiente:
CREATE TRIGGER NOMBREDISP MOMENTODISP EVENTODISP
ON TABLA
FOR EACH ROW SENTENDIADISP

MOMENTODISP -> Cuando entra en acción. Puede ser BEFORE o AFTER
EVENTODISP -> Con qué sentencia se activa dicho trigger. Puede ser INSERT, UPDATE o DELETE

NO SE PUEDEN HACER EN VISTAS!!!
*/

-- Ejemplop trigger: vamos a verificar la altura del cuadro ya que en mi pinacote no caben aquellos que sean más altos que 5.8 de altura
-- PRIMERO NECESITAMOS INCLUIR UN CAMPO EN PINACOTECA QUE INDICQUE ALTURA MAXIMA
ALTER TABLE PINACOTECA
ADD PINA_MAX_ALTO INT;
-- AHORA LA PINACOTECA QUE TENEMOS, LE METEMOS UN MAXIMO
UPDATE PINACOTECA 
SET PINA_MAX_ALTO = 5.8
WHERE PINA_NOMBRE = 'PINA_PRUEBA';
SELECT * FROM PINACOTECA;

USE PINACOTECAS;
-- DELIMITER // -- SIRVE PARA CAMBIAR EL INDICADOR DE FIN DE LINEA. PASA DE SER DE ; A //
USE PINACOTECAS;
DELIMITER //
CREATE TRIGGER VerificacionAltura
BEFORE INSERT ON CUADRO
FOR EACH ROW
BEGIN
    DECLARE DISPONIBLE INT;
    SELECT PINA_MAX_ALTO INTO DISPONIBLE
    FROM PINACOTECA
    WHERE PINA_NOMBRE = NEW.CUAD_PINA_NOMBRE;
    IF NEW.CUAD_ALTO > DISPONIBLE THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'MUY ALTO EL CUADRO PARA ESTA PINACOTECA';
    END IF;
END;
//
DELIMITER ;
-- SIRVE PARA CAMBIAR EL INDICADOR DE FIN DE LINEA. VOLVEMOS A PONERLO COMO ;

/*
Es importante tener un historico de las tablas para saber los cambios que han ido teniendo. Por ejemplo, ver en que pinacoteca	
estaba antes un cuadro o cosas así
Para ello, hay que crear trigers que cuando se actualice o borre un campo, se carge en esta tabla

*/
-- Creamos otra pinacoteca:
INSERT INTO PINACOTECA(PINA_NOMBRE) VALUES ('PINA_PRUEBA2');
-- Creamos tabla historica de cambio de pinacoteca(direccion) y otra de historico de cuadros
DROP TABLE IF EXISTS PINACOTECA_H;
CREATE TABLE PINACOTECA_H(
PINA_H_NOMBRE VARCHAR(50),
PINA_H_CIUDAD VARCHAR(50),
PINA_H_DIRECCION VARCHAR(100),
PINA_H_SUPERFICIE VARCHAR(50)
);
DROP TABLE IF EXISTS CUADRO_ELIM_H;
CREATE TABLE CUADRO_ELIM_H(
CUAD_ELIM_CODIGO SMALLINT,
CUAD_ELIM_NOMBRE VARCHAR(50),
CUAD_ELIM_ALTO DOUBLE,
CUAD_ELIM_ANCHO DOUBLE,
CUAD_ELIM_FECHA DATE,
CUAD_ELIM_TECNICA VARCHAR(50),
CUAD_ELIM_PINT_CODIGO SMALLINT,
CUAD_ELIM_PINA_NOMBRE VARCHAR(50)
);

-- CREAMOS TRIGGER PARA CUANDO OCURRAN ESTAS SITUACIONES
-- PRIMERO VAMOS A LA DE CUADRO ELIMINADO
DELIMITER //
DROP TRIGGER IF EXISTS CuadroEliminado//
CREATE TRIGGER CuadroEliminado
AFTER DELETE ON CUADRO
FOR EACH ROW
BEGIN
	INSERT INTO CUADRO_ELIM_H VALUES (OLD.CUAD_CODIGO, OLD.CUAD_NOMBRE, OLD.CUAD_ALTO, OLD.CUAD_ANCHO, OLD.CUAD_FECHA, OLD.CUAD_TECNICA, OLD.CUAD_PINT_CODIGO, OLD.CUAD_PINA_NOMBRE);
END;
//
DELIMITER ;

-- PROBAMOS EJECUTANDO UN D ELETE EL CUADROS Y COMPROBAMOS SELECTS:
SELECT * FROM CUADRO;
DELETE FROM CUADRO WHERE CUAD_NOMBRE = 'CUADRO1';
SELECT * FROM CUADRO;
SELECT * FROM CUADRO_ELIM_H;

-- CREAMOS EL TRIGGER DE ACTUALIZACION DE PINACOTECA:
DELIMITER //
DROP TRIGGER IF EXISTS PinaActualizada//
CREATE TRIGGER PinaActualizada
AFTER UPDATE ON PINACOTECA
FOR EACH ROW
BEGIN
	IF OLD.PINA_DIRECCION <> NEW.PINA_DIRECCION THEN
		INSERT INTO PINACOTECA_H VALUES (OLD.PINA_NOMBRE, OLD.PINA_CIUDAD, OLD.PINA_DIRECCION, OLD.PINA_SUPERFICIE);
	END IF;
END;
//
DELIMITER ;

-- PROBAMOS CAMBIOS:
SELECT * FROM PINACOTECA;
UPDATE PINACOTECA SET PINA_DIRECCION = 'PRUEBA4' WHERE PINA_NOMBRE = 'PINA_PRUEBA2';
SELECT * FROM PINACOTECA;
SELECT * FROM PINACOTECA_H;
/* FIN TRIGGERS */

/* PERAPARACIÓN DE LOS DATOS PARA LAS PRUEBAS*/
Set sql_safe_updates = 1; -- Poner a 0 si no deja borrar bien los elementos
DELETE FROM PINTOR WHERE PINT_NOMBRE = 'NOMBRE_PINTOR';
select * from pintor;
INSERT INTO PINACOTECA(PINA_NOMBRE) VALUES ('PINA_PRUEBA');
INSERT INTO CUADRO(CUAD_NOMBRE,CUAD_ALTO, CUAD_ANCHO, CUAD_FECHA, CUAD_TECNICA,CUAD_PINT_CODIGO, CUAD_PINA_NOMBRE) 
VALUES('CUADRO3',6.2,16.4,'0001-01-01','JERRY_TECHNIQUES',1,'PINA_PRUEBA');
SELECT * FROM PINACOTECA;
SELECT * FROM CUADRO;
/* FIN PERAPARACIÓN DE LOS DATOS PARA LAS PRUEBAS*/
/* Fin de creacion de elementos en tablas (Language LMD)*/