/*
- UNIQUE KEY(CAMPO1,campo2,....campon) -> Sirve para cuando hya más de una clave primaria, para hacer una única clave primaria y dejar el resto como claves únicas
- FOREIGN KEY(CAMPO) -> Cuando se usa la clave primaria de una tabla en otra tabla. Va acompañado siempre de 'REFERENCES TABLA(CAMPO)'
- PRIMARY KEY(CAMPO1,campo2,....campon) -> Para identificar la clave primera de una tabla (el distintivo único)
- ON DELETE CASCADE: Sirve para actualizar un campo (que viene de una foreign key) cuando se ha borrado dicho registro de la otra tabla
- ON UPDATE CASCADE: Sirve para actualizar un campo (que viene de una foreign key) cuando se ha actualizado dicho registro de la otra tabla
- ON DELETE RESTRICT: Sirve para eliminar un registro (que viene de una foreign key) cuando se ha borrado dicho registro de la otra tabla
- CHECK: Cuando creamos un campo, se puede poner este atributo a la derecha de su declaración para ver si cumple con los requisitos del campo. Por ejemplo: Si tengo un campo que es número de teléfono, este campo (en españa) no debe superar más de nueve dígitos, no puede empezar por 0,...:
    telefono varchar(9) not null check (telefono REGEXP '^[0-9]{9}$')
- DEFAULT: Cuando creamos un campo, se puede pponer este atributo a la derecha de si declaración indicando con que valor quiere que empieze. Ejemplo:
    telefono varchar(9) default '999999999'
*/

DROP DATABASE IF EXISTS PINACOTECAS;
CREATE DATABASE PINACOTECAS;
USE PINACOTECAS;
CREATE TABLE PINTOR(
PINT_CODIGO SMALLINT AUTO_INCREMENT,
PINT_NOMBRE VARCHAR(50),
PINT_PAIS VARCHAR(50),
PINT_CIUDAD VARCHAR(50),
PINT_FEC_NAC DATE,
PINT_FEC_DEF DATE,
PINT_COD_MAESTRO SMALLINT,
PRIMARY KEY(PINT_CODIGO),
FOREIGN KEY(PINT_COD_MAESTRO) REFERENCES PINTOR(PINT_CODIGO)
ON DELETE SET NULL
ON UPDATE CASCADE
);
CREATE TABLE MECENAS(
MECE_CODIGO SMALLINT AUTO_INCREMENT,
MECE_NOMBRE VARCHAR(50),
MECE_PAIS VARCHAR(50),
MECE_FEC_NAC DATE,
MECE_FEC_DEF DATE,
PRIMARY KEY(MECE_CODIGO)
);
CREATE TABLE PINACOTECA(
PINA_NOMBRE VARCHAR(50),
PINA_CIUDAD VARCHAR(50),
PINA_DIRECCION VARCHAR(100),
PINA_SUPERFICIE VARCHAR(50),
PRIMARY KEY(PINA_NOMBRE)
);
CREATE TABLE CUADRO(
CUAD_CODIGO SMALLINT AUTO_INCREMENT,
CUAD_NOMBRE VARCHAR(50),
CUAD_ALTO DOUBLE,
CUAD_ANCHO DOUBLE,
CUAD_FECHA DATE,
CUAD_TECNICA VARCHAR(50),
CUAD_PINT_CODIGO SMALLINT,
CUAD_PINA_NOMBRE VARCHAR(50),
PRIMARY KEY(CUAD_CODIGO),
FOREIGN KEY(CUAD_PINT_CODIGO) REFERENCES PINTOR(PINT_CODIGO)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(CUAD_PINA_NOMBRE) REFERENCES PINACOTECA(PINA_NOMBRE)
ON DELETE RESTRICT
ON UPDATE CASCADE
);
CREATE TABLE ESCUELA(
ESCU_NOMBRE VARCHAR(50),
ESCU_PAIS VARCHAR(50),
ESCU_FEC_APARICION DATE,
PRIMARY KEY(ESCU_NOMBRE)
);
CREATE TABLE PROTEGE(
PROT_MECE_CODIGO SMALLINT,
PROT_PINT_CODIGO SMALLINT,
PRIMARY KEY(PROT_MECE_CODIGO,PROT_PINT_CODIGO),
FOREIGN KEY(PROT_PINT_CODIGO) REFERENCES PINTOR(PINT_CODIGO)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(PROT_MECE_CODIGO) REFERENCES MECENAS(MECE_CODIGO)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE PERTENECE(
PERT_PINT_CODIGO SMALLINT,
PERT_ESCU_NOMBRE VARCHAR(50),
PRIMARY KEY(PERT_PINT_CODIGO),
FOREIGN KEY(PERT_PINT_CODIGO) REFERENCES PINTOR(PINT_CODIGO)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(PERT_ESCU_NOMBRE) REFERENCES ESCUELA(ESCU_NOMBRE)
ON DELETE CASCADE
ON UPDATE CASCADE
)

